### ISSUE TITLE
What's the matter？this may be a bug?

### ISSUE THREAD

**Issue by Lookforworld** [pywinrt/pywinrt#15]
@dlech 
my code :
```python
#-*- coding: utf-8 -*-
import asyncio 
from winrt.windows.graphics import capture as cp
async def getItem():
    pk=cp.GraphicsCapturePicker()  
    itm = await pk.pick_single_item_async()
    return itm
itm0= asyncio.run(getItem())
print(itm0)
```

raise erro: 'utf-8' codec can't decode byte 0xbc in position 235: invalid start byte
what can i do？Thank you for answering questions in your busy schedule！

**Comment by dlech** [comment]
Can you share the full stack trace of the error?

**Comment by Lookforworld** [comment]
> 

Thank you for answering questions! 
The full stack trace:
```
Traceback (most recent call last):
  File "_pydevd_bundle/pydevd_cython.pyx", line 532, in _pydevd_bundle.pydevd_cython.PyDBFrame._handle_exception
  File "D:\Anaconda3\envs\fishing\lib\linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
  File "D:\Anaconda3\envs\fishing\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "D:\Anaconda3\envs\fishing\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "D:\Anaconda3\envs\fishing\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 235: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\fishing\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\fishing\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\program files\microsoft visual studio\2022\enterprise\common7\ide\extensions\microsoft\python\core\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\program files\microsoft visual studio\2022\enterprise\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\program files\microsoft visual studio\2022\enterprise\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "D:\Anaconda3\envs\fishing\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Anaconda3\envs\fishing\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Anaconda3\envs\fishing\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Project\python\fishing\fishing.py", line 24, in <module>
  File "_pydevd_bundle/pydevd_cython.pyx", line 1366, in _pydevd_bundle.pydevd_cython.SafeCallWrapper.__call__
  File "_pydevd_bundle/pydevd_cython.pyx", line 322, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_exception
  File "_pydevd_bundle/pydevd_cython.pyx", line 452, in _pydevd_bundle.pydevd_cython.PyDBFrame.handle_user_exception
  File "_pydevd_bundle/pydevd_cython.pyx", line 535, in _pydevd_bundle.pydevd_cython.PyDBFrame._handle_exception
  File "D:\Anaconda3\envs\fishing\lib\linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
  File "D:\Anaconda3\envs\fishing\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "D:\Anaconda3\envs\fishing\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "D:\Anaconda3\envs\fishing\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 235: invalid start byte
```

I looked at the official API documentation, and I wondered if the question had something to do with the "In a desktop app, before using an instance of this class in a way that displays UI, you'll need to associate the object with its owner's window handle. " mentioned in the documentation.It's called "Call interop APIs"！
Here's the [link.](https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/display-ui-objects#winui-3-with-c)
But I did not find from your tutorial how to deal with this situation.
Thank you for your patient answer！

**Comment by dlech** [comment]
The stack trace looks like a crash in the debugger and not related to the example code.

> mentioned in the documentation.It's called "Call interop APIs"！

We have an issue open about documenting how to do this in Python at https://github.com/pywinrt/python-winsdk/issues/3

**Comment by Lookforworld** [comment]
@dlech 
> 
Thank you very much. I changed the IDE, and this error did not occur again. I modified my code according to your suggestion, and it works good!
It was careless of me-.-!
