### ISSUE TITLE
winrt-runtime install from source with pip fails in MSYS CLANG64

### ISSUE THREAD

**Issue by mimi89999** [pywinrt/pywinrt#47]
Please see the attached log: [winrt-runtime_install_log.txt](https://github.com/pywinrt/pywinrt/files/14804124/aaa.txt)

**Comment by dlech** [comment]
Extracted logs:

```
2024-03-29T13:14:37,648 Using pip 23.2.1 from C:/msys64/clang64/lib/python3.11/site-packages/pip (python 3.11)
2024-03-29T13:14:37,650 Non-user install because site-packages writeable
2024-03-29T13:14:37,690 Created temporary directory: C:/msys64/tmp/pip-build-tracker-xn9gbibe
2024-03-29T13:14:37,690 Initialized build tracking at C:/msys64/tmp/pip-build-tracker-xn9gbibe
2024-03-29T13:14:37,690 Created build tracker: C:/msys64/tmp/pip-build-tracker-xn9gbibe
2024-03-29T13:14:37,690 Entered build tracker: C:/msys64/tmp/pip-build-tracker-xn9gbibe
2024-03-29T13:14:37,692 Created temporary directory: C:/msys64/tmp/pip-install-vmq73nhn
2024-03-29T13:14:37,692 Created temporary directory: C:/msys64/tmp/pip-ephem-wheel-cache-ojey7l7_
2024-03-29T13:14:37,730 Processing c:/msys64/home/michel/winrt-runtime-2.0.0b2
2024-03-29T13:14:37,732   Added file:///C://msys64/home/Michel/winrt-runtime-2.0.0b2 to build tracker 'C:/msys64/tmp/pip-build-tracker-xn9gbibe'
2024-03-29T13:14:37,735   Created temporary directory: C:/msys64/tmp/pip-build-env-9ajf6k69
2024-03-29T13:14:37,736   Running command pip subprocess to install build dependencies
2024-03-29T13:14:38,355   Using pip 23.2.1 from C:/msys64/clang64/lib/python3.11/site-packages/pip (python 3.11)
2024-03-29T13:14:39,046   Collecting setuptools
2024-03-29T13:14:39,046     Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/92/e1/1c8bb3420105e70bdf357d57dd5567202b4ef8d27f810e98bb962d950834/setuptools-69.2.0-py3-none-any.whl.metadata
2024-03-29T13:14:39,048     Using cached setuptools-69.2.0-py3-none-any.whl.metadata (6.3 kB)
2024-03-29T13:14:39,138   Collecting setuptools-scm
2024-03-29T13:14:39,140     Obtaining dependency information for setuptools-scm from https://files.pythonhosted.org/packages/0e/a3/b9a8b0adfe672bf0df5901707aa929d30a97ee390ba651910186776746d2/setuptools_scm-8.0.4-py3-none-any.whl.metadata
2024-03-29T13:14:39,142     Using cached setuptools_scm-8.0.4-py3-none-any.whl.metadata (6.4 kB)
2024-03-29T13:14:39,276   Collecting winrt-sdk
2024-03-29T13:14:39,276     Obtaining dependency information for winrt-sdk from https://files.pythonhosted.org/packages/53/1e/b544511934a7a58598dc4efa249c53aac6412daa834118f08c3776e2eb67/winrt_sdk-2.0.0b2-py3-none-any.whl.metadata
2024-03-29T13:14:39,278     Using cached winrt_sdk-2.0.0b2-py3-none-any.whl.metadata (1.3 kB)
2024-03-29T13:14:39,402   Collecting packaging>=20 (from setuptools-scm)
2024-03-29T13:14:39,402     Obtaining dependency information for packaging>=20 from https://files.pythonhosted.org/packages/49/df/1fceb2f8900f8639e278b056416d49134fb8d84c5942ffaa01ad34782422/packaging-24.0-py3-none-any.whl.metadata
2024-03-29T13:14:39,405     Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
2024-03-29T13:14:39,460   Collecting typing-extensions (from setuptools-scm)
2024-03-29T13:14:39,462     Obtaining dependency information for typing-extensions from https://files.pythonhosted.org/packages/f9/de/dc04a3ea60b22624b51c703a84bbe0184abcd1d0b9bc8074b5d6b7ab90bb/typing_extensions-4.10.0-py3-none-any.whl.metadata
2024-03-29T13:14:39,465     Using cached typing_extensions-4.10.0-py3-none-any.whl.metadata (3.0 kB)
2024-03-29T13:14:39,488   Using cached setuptools-69.2.0-py3-none-any.whl (821 kB)
2024-03-29T13:14:39,492   Using cached setuptools_scm-8.0.4-py3-none-any.whl (42 kB)
2024-03-29T13:14:39,506   Using cached winrt_sdk-2.0.0b2-py3-none-any.whl (5.2 MB)
2024-03-29T13:14:39,521   Using cached packaging-24.0-py3-none-any.whl (53 kB)
2024-03-29T13:14:39,523   Using cached typing_extensions-4.10.0-py3-none-any.whl (33 kB)
2024-03-29T13:14:39,818   Installing collected packages: winrt-sdk, typing-extensions, setuptools, packaging, setuptools-scm
2024-03-29T13:14:44,126   Successfully installed packaging-24.0 setuptools-69.2.0 setuptools-scm-8.0.4 typing-extensions-4.10.0 winrt-sdk-2.0.0b2
2024-03-29T13:14:44,275   Running command Getting requirements to build wheel
2024-03-29T13:14:44,582   WARNING setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section
2024-03-29T13:14:44,745   running egg_info
2024-03-29T13:14:44,746   writing src/winrt_runtime.egg-info/PKG-INFO
2024-03-29T13:14:44,748   writing dependency_links to src/winrt_runtime.egg-info/dependency_links.txt
2024-03-29T13:14:44,750   writing top-level names to src/winrt_runtime.egg-info/top_level.txt
2024-03-29T13:14:44,756   package init file 'src/winrt/__init__.py' not found (or not a regular file)
2024-03-29T13:14:44,795   ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
2024-03-29T13:14:44,796   reading manifest file 'src/winrt_runtime.egg-info/SOURCES.txt'
2024-03-29T13:14:44,800   writing manifest file 'src/winrt_runtime.egg-info/SOURCES.txt'
2024-03-29T13:14:44,852   Running command pip subprocess to install backend dependencies
2024-03-29T13:14:45,461   Using pip 23.2.1 from C:/msys64/clang64/lib/python3.11/site-packages/pip (python 3.11)
2024-03-29T13:14:45,944   Collecting wheel
2024-03-29T13:14:45,944     Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/7d/cd/d7460c9a869b16c3dd4e1e403cce337df165368c71d6af229a74699622ce/wheel-0.43.0-py3-none-any.whl.metadata
2024-03-29T13:14:45,946     Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
2024-03-29T13:14:45,958   Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
2024-03-29T13:14:46,090   Installing collected packages: wheel
2024-03-29T13:14:46,326     Creating C:/msys64/tmp/pip-build-env-9ajf6k69/normal/bin
2024-03-29T13:14:46,378   Successfully installed wheel-0.43.0
2024-03-29T13:14:46,490   Created temporary directory: C:/msys64/tmp/pip-modern-metadata-8ax_fqv2
2024-03-29T13:14:46,490   Running command Preparing metadata (pyproject.toml)
2024-03-29T13:14:46,782   WARNING setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section
2024-03-29T13:14:46,958   running dist_info
2024-03-29T13:14:46,958   creating C:/msys64/tmp/pip-modern-metadata-8ax_fqv2/winrt_runtime.egg-info
2024-03-29T13:14:46,962   writing C:/msys64/tmp/pip-modern-metadata-8ax_fqv2/winrt_runtime.egg-info/PKG-INFO
2024-03-29T13:14:46,964   writing dependency_links to C:/msys64/tmp/pip-modern-metadata-8ax_fqv2/winrt_runtime.egg-info/dependency_links.txt
2024-03-29T13:14:46,964   writing top-level names to C:/msys64/tmp/pip-modern-metadata-8ax_fqv2/winrt_runtime.egg-info/top_level.txt
2024-03-29T13:14:46,966   writing manifest file 'C:/msys64/tmp/pip-modern-metadata-8ax_fqv2/winrt_runtime.egg-info/SOURCES.txt'
2024-03-29T13:14:46,970   package init file 'src/winrt/__init__.py' not found (or not a regular file)
2024-03-29T13:14:47,006   ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
2024-03-29T13:14:47,006   reading manifest file 'C:/msys64/tmp/pip-modern-metadata-8ax_fqv2/winrt_runtime.egg-info/SOURCES.txt'
2024-03-29T13:14:47,010   writing manifest file 'C:/msys64/tmp/pip-modern-metadata-8ax_fqv2/winrt_runtime.egg-info/SOURCES.txt'
2024-03-29T13:14:47,010   creating 'C:/msys64/tmp/pip-modern-metadata-8ax_fqv2/winrt_runtime-2.0.0b2.dist-info'
2024-03-29T13:14:47,090   Source in c:/msys64/home/michel/winrt-runtime-2.0.0b2 has version 2.0.0b2, which satisfies requirement winrt-runtime==2.0.0b2 from file:///C://msys64/home/Michel/winrt-runtime-2.0.0b2
2024-03-29T13:14:47,090   Removed winrt-runtime==2.0.0b2 from file:///C://msys64/home/Michel/winrt-runtime-2.0.0b2 from build tracker 'C:/msys64/tmp/pip-build-tracker-xn9gbibe'
2024-03-29T13:14:47,095 Created temporary directory: C:/msys64/tmp/pip-unpack-bi3ymqci
2024-03-29T13:14:47,095 Building wheels for collected packages: winrt-runtime
2024-03-29T13:14:47,095   Created temporary directory: C:/msys64/tmp/pip-wheel-a9khu3e_
2024-03-29T13:14:47,095   Destination directory: C:/msys64/tmp/pip-wheel-a9khu3e_
2024-03-29T13:14:47,098   Running command Building wheel for winrt-runtime (pyproject.toml)
2024-03-29T13:14:47,391   WARNING setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section
2024-03-29T13:14:47,567   running bdist_wheel
2024-03-29T13:14:47,575   running build
2024-03-29T13:14:47,575   running build_py
2024-03-29T13:14:47,575   package init file 'src/winrt/__init__.py' not found (or not a regular file)
2024-03-29T13:14:47,579   running egg_info
2024-03-29T13:14:47,579   writing src/winrt_runtime.egg-info/PKG-INFO
2024-03-29T13:14:47,583   writing dependency_links to src/winrt_runtime.egg-info/dependency_links.txt
2024-03-29T13:14:47,583   writing top-level names to src/winrt_runtime.egg-info/top_level.txt
2024-03-29T13:14:47,618   ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
2024-03-29T13:14:47,618   reading manifest file 'src/winrt_runtime.egg-info/SOURCES.txt'
2024-03-29T13:14:47,624   writing manifest file 'src/winrt_runtime.egg-info/SOURCES.txt'
2024-03-29T13:14:47,626   running build_ext
2024-03-29T13:14:47,630   error: [WinError 2] Le fichier spécifié est introuvable
2024-03-29T13:14:47,679   ERROR: [present-rich] Building wheel for winrt-runtime (pyproject.toml) exited with 1
2024-03-29T13:14:47,684   [bold magenta]full command[/]: [blue]C:/msys64/clang64/bin/python.exe C:/msys64/clang64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel C:/msys64/tmp/tmpvpvrb9xz[/]
2024-03-29T13:14:47,684   [bold magenta]cwd[/]: C:/msys64/home/Michel/winrt-runtime-2.0.0b2
2024-03-29T13:14:47,684   ERROR: Failed building wheel for winrt-runtime
2024-03-29T13:14:47,687 Failed to build winrt-runtime
2024-03-29T13:14:47,687 ERROR: Could not build wheels for winrt-runtime, which is required to install pyproject.toml-based projects
2024-03-29T13:14:47,687 Exception information:
2024-03-29T13:14:47,687 Traceback (most recent call last):
2024-03-29T13:14:47,687   File "C:/msys64/clang64/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
2024-03-29T13:14:47,687     status = run_func(*args)
2024-03-29T13:14:47,687              ^^^^^^^^^^^^^^^
2024-03-29T13:14:47,687   File "C:/msys64/clang64/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
2024-03-29T13:14:47,687     return func(self, options, args)
2024-03-29T13:14:47,687            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-29T13:14:47,687   File "C:/msys64/clang64/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 429, in run
2024-03-29T13:14:47,687     raise InstallationError(
2024-03-29T13:14:47,687 pip._internal.exceptions.InstallationError: Could not build wheels for winrt-runtime, which is required to install pyproject.toml-based projects
2024-03-29T13:14:47,704 Remote version of pip: 24.0
2024-03-29T13:14:47,704 Local version of pip:  23.2.1
2024-03-29T13:14:47,706 Was pip installed by pip? False
2024-03-29T13:14:47,706 Removed build tracker: 'C:/msys64/tmp/pip-build-tracker-xn9gbibe'
```

**Comment by mimi89999** [comment]
Hello,
Thanks for fixing this! I saw that a new version was tagged, but isn't available on PyPi.

**Comment by dlech** [comment]
Yeah, unfortunately the build failed.
