### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by elibroftw** [pywinrt/pywinrt#49]
```sh
pip install winrt
ERROR: Could not find a version that satisfies the requirement winrt (from versions: none)
ERROR: No matching distribution found for winrt
```

I installed `winrt-runtime` and  `winrt-Windows.Media` but

```py
import winrt.windows.media
```

```py
Traceback (most recent call last):
  File "c:\Users\maste\Documents\GitHub\music-caster\src\music_caster.py", line 3862, in <module>
    system_media_controls = SystemMediaControls()
                            ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\maste\Documents\GitHub\music-caster\src\modules\win32_media_controls.py", line 8, in __init__
    import winrt.windows.media
ModuleNotFoundError: No module named 'winrt'
```

**Comment by elibroftw** [comment]
I guess being in a virtualenv is a problem?

**Comment by dlech** [comment]
To use PyWinRT 2.0, you need to install individual namespace packages now instead of one big monolithic package. For example:

    pip install winrt-windows.foundation
