### ISSUE TITLE
Add event documentation

### ISSUE THREAD

**Issue by thelulzy** [pywinrt/pywinrt#77]
Events are currently undocumented.

[The events section of the documentation](https://pywinrt.readthedocs.io/en/latest/types.html#events) has a callout which says the following: 
> Todo
> explain events

___

I'm trying to utilize the `handle_media_properties_changed` event, yet get the following error at the `create_task` call each time the media changes despite having created and set a new event loop, and set the loop to run forever *prior* to the media changing:
```
Exception ignored in: <function handle_media_properties_changed at 0x00000205A048C0E0>
Traceback (most recent call last):
  File "...\test_event_handle.py", line 31, in handle_media_properties_changed
    asyncio.create_task(log_exceptions(get_media_properties(session)))
  File "...\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 417, in create_task
    loop = events.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop 
```

```python
def handle_media_properties_changed(session: Session, args: MediaPropertiesChangedEventArgs) -> None:
    asyncio.create_task(log_exceptions(get_media_properties(session)))

async def get_sessions():
    sessions = await SessionManager.request_async()
    return sessions

if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)

    sessions = asyncio.run(get_sessions())
    current_session = sessions.get_current_session()

    # handle current state
    asyncio.run(get_media_properties(current_session))

    # add callback to handle any future changes
    media_properties_changed_token = current_session.add_media_properties_changed(handle_media_properties_changed)

    print('Waiting until keyboard interrupt')
    try:
        loop.run_forever()
    except KeyboardInterrupt:
        # remove the callback
        current_session.remove_media_properties_changed(media_properties_changed_token)
        print('Callback removed')
        pass
```

I've also tried explictly getting and setting the currently running loop from within `handle_media_properties_changed`, which simply moves the `RuntimeError: no running event loop` exception to my explicit call.
```python
def handle_media_properties_changed(session: Session, args: MediaPropertiesChangedEventArgs) -> None:
    asyncio.set_event_loop(asyncio.get_running_loop())
    print('Creating task')
    asyncio.create_task(log_exceptions(get_media_properties(session)))
    # asyncio.create_task(get_media_properties(session))
    print('Created task')
```    

How is there no running event loop if `loop` is currently running forever?

**Comment by dlech** [comment]
> Events are currently undocumented.

There is some documentation hiding at https://github.com/pywinrt/pywinrt/blob/main/projection/readme.md#event-handlers



> How is there no running event loop if `loop` is currently running forever?

WinRT does callbacks on a different thread, so you need to capture the running loop and use `loop.call_soon_threadsafe()` in the event handler.

Also, each `asyncio.run()` creates a new loop, so you will need to rewrite things so there is only one `asyncio.run()` for the whole application.
